option('static_dlls',  type : 'boolean', value : false, description: 'Build d3d9/d3d8 as static libraries (no version scripts, no pkg-config)')
option('enable_dxgi',  type : 'boolean', value : true, description: 'Build DXGI')
option('enable_d3d8',  type : 'boolean', value : true, description: 'Build D3D8')
option('enable_d3d9',  type : 'boolean', value : true, description: 'Build D3D9')
option('enable_d3d10', type : 'boolean', value : true, description: 'Build D3D10')
option('enable_d3d11', type : 'boolean', value : true, description: 'Build D3D11')
option('build_id',     type : 'boolean', value : false)
option('gipa_symbol',  type : 'string',  value : '',    description: 'Use this extern vkGetInstanceProcAddr-compatible symbol instead of loading libvulkan')
option('native_glfw',  type : 'feature', value : 'auto', description: 'Enable GLFW WSI for DXVK Native')
option('native_sdl2',  type : 'feature', value : 'auto', description: 'Enable SDL2 WSI for DXVK Native')
option('native_sdl3',  type : 'feature', value : 'auto', description: 'Enable SDL3 WSI for DXVK Native')
option('native_headless', type : 'feature', value : 'disabled', description: 'Enable headless WSI for DXVK Native (VK_EXT_headless_surface, no window system)')
